name: Build API

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    defaults:
      run:
        working-directory: ./src/Richter.THEC
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal



  docker:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/Richter.THEC/Richter.THEC.Api
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build --file Dockerfile --tag richterthecapi:build ..
    - name: Run the Docker image
      run: docker run -d -p 8080:80 --name richterthecapi --env ASPNETCORE_ENVIRONMENT=Development richterthecapi:build
    - name: Test the Docker container
      run: |
        curl -X POST \
        http://0.0.0.0:8080/api/distance \
        -H "Content-Type: application/json" \
        -d '{"provider":"Yellow","distance":10,"when":"2021-12-05T17:29:11.670Z"}'
